### PR TITLE
Sampling rossk suggested changes

### PR DESCRIPTION
**Pull request by RossKohler**
Suggested changes for sampling component.

- Renamed component to 'sampler' as it would be used for under/oversampling.
- Changed IO operations to TF operations, these work for local + GCS buckets.
- Added parameter to configure the component for over/under sampling
- Changed component to inherit from TFX base beam component

### CODE REVIEW

**Comment by RossKohler** [comment]
@kindalime here's my suggested changes. Let me know what you think.

**Comment by kindalime** [comment]
The PR looks great! I'll merge it momentarily.

**Comment by kindalime** [comment]
Just merged the branch on local - thank you very much for your help!

**Comment by RossKohler** [comment]
@kindalime no problem, let me know when you've pushed to a branch so I can pull the changes 👍 if there's anything else I can help with, let me know :)

**Pull request closed without merging**
